# Generated by Django 2.1.5 on 2019-02-02 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('piece', models.CharField(choices=[('table', 'Bord'), ('stump', 'Stubbe')], max_length=32, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['uploaded'],
            },
        ),
    ]
